# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Browserless path exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ browserless_uid }}"
    group: "{{ browserless_gid }}"
  with_items:
    - "{{ browserless_base_path }}"

- name: Ensure Browserless support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ browserless_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ browserless_uid }}"
    group: "{{ browserless_gid }}"
  with_items:
    - env
    - labels
  register: browserless_support_files_result

- name: Ensure Browserless container image is pulled via community.docker.docker_image
  when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
  community.docker.docker_image:
    name: "{{ browserless_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ browserless_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else browserless_container_image_force_pull }}"
  register: browserless_container_image_pull_result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: browserless_container_image_pull_result is not failed

- name: Ensure Browserless container image is pulled via ansible.builtin.command
  when: devture_systemd_docker_base_container_image_pull_method == 'command'
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ browserless_container_image }}"
  register: browserless_container_image_pull_result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: browserless_container_image_pull_result is not failed
  changed_when: "'Downloaded newer image' in result.stdout"

- name: Ensure Browserless container network is created via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ browserless_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"
  register: browserless_network_creation_result

- name: Ensure Browserless container network is created via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} network create
      {% if devture_systemd_docker_base_ipv6_enabled %}--ipv6{% endif %}
      {{ devture_systemd_docker_base_container_networks_driver_options_string }}
      {{ browserless_container_network }}
  register: browserless_network_creation_result
  changed_when: browserless_network_creation_result.rc == 0
  failed_when: browserless_network_creation_result.rc != 0 and 'already exists' not in browserless_network_creation_result.stderr

- name: Ensure Browserless systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/browserless.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ browserless_identifier }}.service"
    mode: "0644"
  register: browserless_systemd_service_result

- name: Determine whether Browserless needs a restart
  ansible.builtin.set_fact:
    browserless_restart_necessary: >-
      {{
        browserless_support_files_result.changed | default(false)
        or browserless_systemd_service_result.changed | default(false)
        or browserless_container_image_pull_result.changed | default(false)
      }}
